/* =========================================================================
   Serveur de l'analyseur de niches KDP (abonnement + crédits)
   - /health           : test de vie
   - /verifier-licence : état d'une clé (abonnement ? crédits ? essai ?)
   - /analyse          : vérifie droits + quota, puis appelle Gemini (pool de clés)

   Ordre de consommation d'une recherche :
     1) quota MENSUEL de l'abonnement (si abonné et quota restant)
     2) CRÉDITS non expirants (si solde > 0)
     3) ESSAI gratuit annuel par appareil (si aucune licence)
   ========================================================================= */
// Chargement simple du .env (sans dépendance) pour les tests locaux.
(function loadEnv() {
  try {
    const fs = require("fs"), path = require("path");
    const p = path.join(__dirname, ".env");
    if (!fs.existsSync(p)) return;
    for (const line of fs.readFileSync(p, "utf8").split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
      if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2];
    }
  } catch (_) {}
})();

const express = require("express");
const cors = require("cors");
const crypto = require("crypto");
const { generate } = require("./aiprovider");
const { checkLicense } = require("./license");
const store = require("./store");
const lof = require("./lof");

const app = express();
app.set("trust proxy", true); // Render est derrière un proxy -> vraie IP dans X-Forwarded-For
app.use(cors());
app.use(express.json({ limit: "1mb" }));

const PORT = process.env.PORT || 8787;

/* --- Garde-fou essai gratuit par IP (hachée, jamais stockée en clair) ------
   Par défaut : l'essai gratuit est réclamable UNE SEULE FOIS PAR IP, à vie.
   Réglable par variables d'environnement :
     TRIAL_IP_GUARD = on | off        (défaut on)
     TRIAL_IP_MODE  = lifetime | year (défaut lifetime)
     TRIAL_IP_MAX   = nombre d'unités gratuites autorisées par IP (défaut = essai)
   Assouplir = mettre TRIAL_IP_MODE=year ou augmenter TRIAL_IP_MAX. */
function ipGuardOn() { return String(process.env.TRIAL_IP_GUARD || "on").toLowerCase() !== "off"; }
function clientIp(req) {
  const xf = (req.headers["x-forwarded-for"] || "").split(",")[0].trim();
  return xf || req.ip || req.socket?.remoteAddress || "";
}
function ipHash(req) {
  const salt = process.env.IP_SALT || "eclozia-lof";
  return crypto.createHash("sha256").update(salt + "|" + clientIp(req)).digest("hex").slice(0, 24);
}
function ipMax() {
  const n = parseInt(process.env.TRIAL_IP_MAX || "", 10);
  return Number.isFinite(n) && n > 0 ? n : require("./license").planLimits().trial;
}

app.get("/health", (_req, res) => {
  res.json({ ok: true, service: "kdp-analyzer-server", time: new Date().toISOString() });
});

// Page d'accueil simple (utile pour vérifier que le service tourne)
app.get("/", (_req, res) => {
  res.type("html").send(
    `<!doctype html><meta charset="utf-8"><title>Analyseur KDP</title>
     <div style="font:16px/1.5 system-ui;max-width:640px;margin:60px auto;padding:0 20px">
     <h1>Analyseur de niches KDP</h1>
     <p>Le service fonctionne ✅</p>
     <p><a href="/confidentialite">Politique de confidentialité</a></p>
     </div>`
  );
});

// Politique de confidentialité / Privacy policy (bilingue EN + FR)
app.get(["/confidentialite", "/privacy"], (_req, res) => {
  const email = process.env.SUPPORT_EMAIL || "ton-email@exemple.com";
  const maj = new Date().toISOString().slice(0, 10);
  res.type("html").send(`<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy Policy / Politique de confidentialité — KDP Niche Analyzer</title>
<style>body{font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;
max-width:760px;margin:40px auto;padding:0 20px;color:#1a1a1a}
h1{font-size:24px}h2{font-size:18px;margin-top:28px}
.small{color:#666;font-size:14px}code{background:#f2f2ef;padding:1px 5px;border-radius:4px}
.switch{margin:0 0 18px}.switch button{font:inherit;cursor:pointer;border:1px solid #ccc;
background:#fff;border-radius:8px;padding:6px 14px;margin-right:6px}
.switch button.on{background:#2f6f4f;color:#fff;border-color:#2f6f4f}</style>
</head><body>
<div class="switch">
  <button id="bEN" onclick="show('en')">English</button>
  <button id="bFR" onclick="show('fr')">Français</button>
</div>

<div id="en">
<h1>Privacy Policy</h1>
<p class="small">“KDP Niche Analyzer” extension — last updated: ${maj}</p>
<p>This extension helps you analyze book niches on Amazon. This page explains what data
is processed and why. We collect the strict minimum and never sell any data.</p>
<h2>1. Data processed</h2>
<ul>
<li><b>Anonymous device ID</b>: a random identifier (generated by the extension) used
only to count free-trial searches. It contains no personal information and cannot
identify you.</li>
<li><b>License key</b>: if you are a subscriber or bought credits, your key is sent to
the server to verify your access and quota.</li>
<li><b>Analysis data</b>: when you run an analysis, the public information on the Amazon
page you are viewing (titles, prices, public rankings) and your request are sent to our
server and then to our AI provider (Google Gemini or Mistral AI) to generate the analysis.</li>
<li><b>Business search (LocalScout)</b>: when you run an integrated local search, your query
(business type, city) is sent to Google Places API to obtain the list of matching public
businesses; the public website of each business you choose to analyze is then audited.</li>
<li><b>Hashed IP</b>: to prevent free-trial abuse, a one-way hash of your IP address is
stored as an anti-abuse counter. The IP itself is never stored in clear text.</li>
</ul>
<h2>2. What we do NOT do</h2>
<ul>
<li>No selling or renting of data to third parties.</li>
<li>No advertising.</li>
<li>No collection of browsing data outside the Amazon pages you analyze voluntarily.</li>
<li>No payment data is handled by the extension: payments are processed by our provider (Gumroad).</li>
</ul>
<h2>3. Sub-processors</h2>
<ul>
<li><b>Google (Gemini API)</b> and <b>Mistral AI (API)</b> — AI generation of the analyses.</li>
<li><b>Google Places API</b> — integrated local business search (LocalScout only).</li>
<li><b>Gumroad</b> — payments, tax and license management.</li>
<li><b>Server host</b> — running the service.</li>
</ul>
<h2>4. Retention</h2>
<p>Usage counters (trial, monthly quota, credits) are kept as long as needed to manage
your access to the service.</p>
<h2>5. Your rights</h2>
<p>You can request access to or deletion of your data by writing to:
<a href="mailto:${email}">${email}</a>.</p>
<h2>6. Contact</h2>
<p>For any question: <a href="mailto:${email}">${email}</a>.</p>
</div>

<div id="fr" hidden>
<h1>Politique de confidentialité</h1>
<p class="small">Extension « KDP Niche Analyzer » — dernière mise à jour : ${maj}</p>
<p>Cette extension aide à analyser des niches de livres sur Amazon. Cette page explique
quelles données sont traitées et pourquoi. Nous collectons le strict minimum et ne
vendons aucune donnée.</p>
<h2>1. Données traitées</h2>
<ul>
<li><b>Identifiant d'appareil anonyme</b> : un identifiant aléatoire (généré par
l'extension) sert uniquement à compter les recherches de l'essai gratuit. Il ne
contient aucune information personnelle et ne permet pas de vous identifier.</li>
<li><b>Clé de licence</b> : si vous êtes abonné ou avez acheté des crédits, votre clé
est envoyée au serveur pour vérifier vos droits et votre quota.</li>
<li><b>Données d'analyse</b> : lorsque vous lancez une analyse, les informations de la
page Amazon consultée (titres, prix, classements publics) et votre demande sont
envoyées à notre serveur, puis à notre fournisseur d'IA (Google Gemini ou Mistral AI), afin de générer l'analyse.</li>
<li><b>Recherche d'entreprises (LocalScout)</b> : lors d'une recherche locale intégrée, votre
requête (type d'entreprise, ville) est envoyée à l'API Google Places pour obtenir la liste
des entreprises publiques correspondantes ; le site public de chaque entreprise que vous
choisissez d'analyser est ensuite audité.</li>
<li><b>IP hachée</b> : pour éviter l'abus de l'essai gratuit, une empreinte à sens unique de
votre adresse IP est conservée comme compteur anti-abus. L'IP elle-même n'est jamais
stockée en clair.</li>
</ul>
<h2>2. Ce que nous ne faisons pas</h2>
<ul>
<li>Aucune vente ni location de données à des tiers.</li>
<li>Aucune publicité.</li>
<li>Aucune collecte de données de navigation en dehors des pages Amazon que vous
analysez volontairement.</li>
<li>Aucune donnée de paiement n'est traitée par l'extension : les paiements sont gérés
par notre prestataire (Gumroad).</li>
</ul>
<h2>3. Prestataires (sous-traitants)</h2>
<ul>
<li><b>Google (API Gemini)</b> et <b>Mistral AI (API)</b> — génération des analyses par IA.</li>
<li><b>API Google Places</b> — recherche locale intégrée d'entreprises (LocalScout uniquement).</li>
<li><b>Gumroad</b> — paiement, TVA et gestion des licences.</li>
<li><b>Hébergeur du serveur</b> — exécution du service.</li>
</ul>
<h2>4. Conservation</h2>
<p>Les compteurs d'usage (essai, quota mensuel, crédits) sont conservés le temps
nécessaire à la gestion de votre accès au service.</p>
<h2>5. Vos droits</h2>
<p>Vous pouvez demander l'accès à vos données ou leur suppression en écrivant à :
<a href="mailto:${email}">${email}</a>.</p>
<h2>6. Contact</h2>
<p>Pour toute question : <a href="mailto:${email}">${email}</a>.</p>
</div>

<script>
function show(l){document.getElementById('en').hidden=(l!=='en');
document.getElementById('fr').hidden=(l!=='fr');
document.getElementById('bEN').className=(l==='en'?'on':'');
document.getElementById('bFR').className=(l==='fr'?'on':'');}
show((navigator.language||'en').slice(0,2).toLowerCase()==='fr'?'fr':'en');
</script>
</body></html>`);
});

/* Construit un résumé de l'état d'une clé (pour l'extension). */
async function statusFor(license, deviceId) {
  const info = await checkLicense(license);

  if (info.kind === "error") {
    return { error: "verification_indisponible" };
  }
  if (info.kind === "dev") {
    const used = await store.getMonthly("dev");
    return {
      active: true, plan: "dev", limit: info.limit, used,
      restant: Math.max(0, info.limit - used), resetsAt: store.monthlyResetsAt(),
    };
  }
  if (info.kind === "subscription") {
    const id = "lic:" + license;
    const used = await store.getMonthly(id);
    const credits = await store.getCredits(license);
    return {
      active: true, plan: "abo", limit: info.limit, used,
      restant: Math.max(0, info.limit - used) + credits,
      credits, resetsAt: store.monthlyResetsAt(),
    };
  }
  if (info.kind === "credits") {
    await store.grantCreditsOnce(license, info.creditGrant); // crédite une seule fois
    const credits = await store.getCredits(license);
    return { active: credits > 0, plan: "credits", credits, restant: credits };
  }
  if (info.kind === "invalid") {
    return { active: false, plan: null, restant: 0 };
  }
  // kind === "none" -> essai gratuit
  const usedTrial = await store.getTrial(deviceId);
  const limitTrial = require("./license").planLimits().trial;
  return {
    active: false, plan: "trial", limit: limitTrial, used: usedTrial,
    restant: Math.max(0, limitTrial - usedTrial), resetsAt: store.trialResetsAt(),
  };
}

// État d'une licence (bouton "Vérifier ma licence" de l'extension)
app.post("/verifier-licence", async (req, res) => {
  try {
    const license = (req.body && req.body.license) || "";
    const deviceId = (req.body && req.body.deviceId) || "";
    res.json(await statusFor(license, deviceId));
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

// Analyse : cœur du service
app.post("/analyse", async (req, res) => {
  try {
    const body = req.body || {};
    const license = body.license || "";
    const deviceId = body.deviceId || "";
    const prompt = body.prompt || "";
    if (!prompt) return res.status(400).json({ ok: false, error: "prompt manquant" });

    const info = await checkLicense(license);

    if (info.kind === "error") {
      return res.status(503).json({
        ok: false, error: "verification_indisponible",
        message: "Vérification de la licence momentanément indisponible. Réessaie dans un instant.",
      });
    }
    if (info.kind === "invalid") {
      return res.status(402).json({
        ok: false, error: "abonnement_inactif",
        message: "Clé invalide, expirée ou annulée. Abonne-toi ou achète un pack de crédits.",
      });
    }
    if (info.kind === "credits") {
      await store.grantCreditsOnce(license, info.creditGrant); // crédite une seule fois
    }

    // Choix du "compteur" à débiter, SANS débiter tout de suite (on ne débite qu'en cas de succès IA).
    const limits = require("./license").planLimits();
    let bucket = null; // "monthly" | "credits" | "trial"
    let ctx = {};

    if (info.kind === "dev") {
      bucket = "dev";
    } else if (info.kind === "subscription") {
      const id = "lic:" + license;
      const used = await store.getMonthly(id);
      if (used < info.limit) { bucket = "monthly"; ctx = { id, limit: info.limit }; }
      else if (await store.getCredits(license) > 0) { bucket = "credits"; }
      else {
        return res.status(429).json({
          ok: false, error: "quota_atteint",
          message: "Quota mensuel atteint. Il se réinitialise le mois prochain, ou achète un pack de crédits.",
          used, limit: info.limit, resetsAt: store.monthlyResetsAt(),
        });
      }
    } else if (info.kind === "credits") {
      if (await store.getCredits(license) > 0) { bucket = "credits"; }
      else {
        return res.status(429).json({
          ok: false, error: "credits_epuises",
          message: "Crédits épuisés. Achète un nouveau pack ou abonne-toi.",
        });
      }
    } else {
      // kind === "none" -> essai gratuit par appareil + garde-fou IP
      if (!deviceId) return res.status(400).json({ ok: false, error: "deviceId requis pour l'essai gratuit" });
      if (ipGuardOn() && (await store.getIpFree(ipHash(req))) >= ipMax()) {
        return res.status(402).json({
          ok: false, error: "essai_ip_epuise",
          message: "Essai gratuit déjà utilisé sur ce réseau. Abonne-toi ou achète un pack de crédits pour continuer.",
        });
      }
      const usedTrial = await store.getTrial(deviceId);
      if (usedTrial < limits.trial) { bucket = "trial"; ctx = { limit: limits.trial }; }
      else {
        return res.status(402).json({
          ok: false, error: "essai_termine",
          message: "Essai gratuit épuisé pour cette année. Abonne-toi ou achète un pack de crédits pour continuer.",
          used: usedTrial, limit: limits.trial, resetsAt: store.trialResetsAt(),
        });
      }
    }

    // Appel IA (pool de clés Gemini, bascule automatique)
    const text = await generate(prompt);

    // On ne débite qu'en cas de succès
    let restant = null, used = null, limit = null, credits = null;
    if (bucket === "monthly") {
      used = await store.incrementMonthly(ctx.id);
      limit = ctx.limit;
      credits = await store.getCredits(license);
      restant = Math.max(0, limit - used) + credits;
    } else if (bucket === "credits") {
      credits = await store.consumeCredit(license);
      restant = credits;
    } else if (bucket === "trial") {
      used = await store.incrementTrial(deviceId);
      if (ipGuardOn()) await store.incrementIpFree(ipHash(req));
      limit = ctx.limit;
      restant = Math.max(0, limit - used);
    } else if (bucket === "dev") {
      used = await store.incrementMonthly("dev");
      limit = info.limit;
      restant = Math.max(0, limit - used);
    }

    res.json({ ok: true, text, used, limit, credits, restant });
  } catch (e) {
    res.status(e.status || 500).json({ ok: false, error: e.message });
  }
});

/* =======================================================================
   LOF — Local Opportunity Finder
   ======================================================================= */

// Liste des playbooks (pour l'extension)
app.get("/lof/playbooks", (_req, res) => {
  const out = {};
  for (const k of Object.keys(lof.PLAYBOOKS)) out[k] = lof.PLAYBOOKS[k].label;
  res.json({ ok: true, playbooks: out });
});

// Combien d'unités (analyses) sont disponibles pour cette licence ?
async function availableUnits(info, license, deviceId, req) {
  const limits = require("./license").planLimits();
  if (info.kind === "dev") return { bucketPlan: "dev", available: 9999 };
  if (info.kind === "subscription") {
    const id = "lic:" + license;
    const used = await store.getMonthly(id);
    const credits = await store.getCredits(license);
    return { bucketPlan: "abo", available: Math.max(0, info.limit - used) + credits, id, limit: info.limit };
  }
  if (info.kind === "credits") {
    const credits = await store.getCredits(license);
    return { bucketPlan: "credits", available: credits };
  }
  // essai gratuit : limité par l'appareil ET par l'IP (garde-fou)
  const usedTrial = await store.getTrial(deviceId);
  let available = Math.max(0, limits.trial - usedTrial);
  if (ipGuardOn()) {
    const ipUsed = await store.getIpFree(ipHash(req));
    available = Math.min(available, Math.max(0, ipMax() - ipUsed));
  }
  return { bucketPlan: "trial", available, limit: limits.trial };
}

// Débite n unités dans le bon ordre (mensuel -> crédits -> essai)
async function spendUnits(info, license, deviceId, n, req) {
  for (let k = 0; k < n; k++) {
    if (info.kind === "dev") { await store.incrementMonthly("dev"); continue; }
    if (info.kind === "subscription") {
      const id = "lic:" + license;
      const used = await store.getMonthly(id);
      if (used < info.limit) await store.incrementMonthly(id);
      else await store.consumeCredit(license);
      continue;
    }
    if (info.kind === "credits") { await store.consumeCredit(license); continue; }
    await store.incrementTrial(deviceId); // trial appareil
    if (ipGuardOn()) await store.incrementIpFree(ipHash(req)); // + garde-fou IP
  }
}

// Recherche intégrée d'entreprises (Google Places, clé côté serveur).
// Ne débite PAS de quota (le débit a lieu à l'analyse), mais exige des unités
// disponibles pour éviter des appels Places illimités (coût Google).
app.post("/lof/search", async (req, res) => {
  try {
    const body = req.body || {};
    const license = body.license || "";
    const deviceId = body.deviceId || "";
    const info = await checkLicense(license);
    if (info.kind === "error")
      return res.status(503).json({ ok: false, error: "verification_indisponible",
        message: "Vérification de la licence momentanément indisponible. Réessaie dans un instant." });
    if (info.kind === "invalid")
      return res.status(402).json({ ok: false, error: "abonnement_inactif",
        message: "Clé invalide, expirée ou annulée. Abonne-toi ou achète un pack de crédits." });
    if (info.kind === "credits") await store.grantCreditsOnce(license, info.creditGrant);
    if (info.kind === "none" && !deviceId)
      return res.status(400).json({ ok: false, error: "deviceId requis pour l'essai gratuit" });

    const av = await availableUnits(info, license, deviceId, req);
    if (av.available <= 0)
      return res.status(402).json({ ok: false, error: "quota_atteint",
        message: "Quota épuisé : abonne-toi ou achète un pack pour lancer une nouvelle recherche.",
        resetsAt: av.bucketPlan === "trial" ? store.trialResetsAt() : store.monthlyResetsAt() });

    // On respecte le nombre demandé (3-20). La recherche Google coûte le même
    // prix qu'elle rende 3 ou 20 résultats ; on ne la bride donc PAS par le quota
    // (le quota est débité seulement à l'analyse). Il suffit d'avoir du quota > 0.
    const max = Math.min(Math.max(1, Number(body.max) || 20), 20);
    try {
      const businesses = await lof.placesSearch({
        query: body.query, category: body.category, city: body.city,
        max, locale: body.locale || "fr", regionCode: body.regionCode,
      });
      res.json({ ok: true, count: businesses.length, available: av.available, businesses, attribution: "Résultats fournis par Google" });
    } catch (e) {
      if (e.status === 501)
        return res.status(501).json({ ok: false, error: "places_non_configure",
          message: "La recherche intégrée n'est pas encore activée. Utilise l'import CSV en attendant." });
      return res.status(e.status || 502).json({ ok: false, error: "places_erreur", message: e.message });
    }
  } catch (e) {
    res.status(e.status || 500).json({ ok: false, error: e.message });
  }
});

// Analyse d'un lot d'entreprises : 1 unité = 1 entreprise analysée
app.post("/lof/analyse", async (req, res) => {
  try {
    const body = req.body || {};
    const license = body.license || "";
    const deviceId = body.deviceId || "";
    const playbook = body.playbook || "site";
    const locale = body.locale || "fr";
    let businesses = Array.isArray(body.businesses) ? body.businesses : [];
    if (!businesses.length) return res.status(400).json({ ok: false, error: "aucune_entreprise" });
    if (businesses.length > 20) businesses = businesses.slice(0, 20); // garde-fou coût/temps

    const info = await checkLicense(license);
    if (info.kind === "error")
      return res.status(503).json({ ok: false, error: "verification_indisponible",
        message: "Vérification de la licence momentanément indisponible. Réessaie dans un instant." });
    if (info.kind === "invalid")
      return res.status(402).json({ ok: false, error: "abonnement_inactif",
        message: "Clé invalide, expirée ou annulée. Abonne-toi ou achète un pack de crédits." });
    if (info.kind === "credits") await store.grantCreditsOnce(license, info.creditGrant);
    if (info.kind === "none" && !deviceId)
      return res.status(400).json({ ok: false, error: "deviceId requis pour l'essai gratuit" });

    const av = await availableUnits(info, license, deviceId, req);
    if (av.available <= 0) {
      const msg = av.bucketPlan === "trial"
        ? "Essai gratuit épuisé. Abonne-toi ou achète un pack de crédits."
        : "Quota atteint. Il se réinitialise le mois prochain, ou achète un pack de crédits.";
      return res.status(402).json({ ok: false, error: "quota_atteint", message: msg,
        resetsAt: av.bucketPlan === "trial" ? store.trialResetsAt() : store.monthlyResetsAt() });
    }

    const toProcess = Math.min(businesses.length, av.available);
    const subset = businesses.slice(0, toProcess);

    // 1) audit + scoring déterministe ; 2) explication IA
    const scored = await lof.scoreBatch(subset, playbook);
    const results = await lof.explain(scored, playbook, locale);

    // Débit après succès
    await spendUnits(info, license, deviceId, toProcess, req);

    // État restant
    let restant = null;
    if (info.kind === "subscription") {
      const id = "lic:" + license;
      const used = await store.getMonthly(id);
      restant = Math.max(0, info.limit - used) + (await store.getCredits(license));
    } else if (info.kind === "credits") restant = await store.getCredits(license);
    else if (info.kind === "none") restant = Math.max(0, (av.limit || 0) - (await store.getTrial(deviceId)));

    res.json({
      ok: true,
      playbook,
      analysed: toProcess,
      skipped: businesses.length - toProcess,
      restant,
      results: results.map((r) => ({ ...r, audit: undefined })), // audit interne masqué
    });
  } catch (e) {
    res.status(e.status || 500).json({ ok: false, error: e.message });
  }
});

app.listen(PORT, () => {
  console.log("KDP Analyzer server en écoute sur le port " + PORT);
  console.log("Mode DEV_OPEN =", String(process.env.DEV_OPEN).toLowerCase() === "true");
  console.log("Stockage =", store.mode === "redis" ? "Redis Upstash (persistant)" : "fichier local");
});
